# Data

We are examining the data set **Credit.csv**, which can be downloaded ([here](http://www-bcf.usc.edu/~gareth/ISL/Credit.csv)), from the book [*An Introduction to Statistical Learning*](http://www-bcf.usc.edu/~gareth/ISL/data.html) by Gareth James, Daniela Witten, Trevor Hastie and Robert Tibshirani.

The data set contains both qualitiative and quantitative variables. The qualitative variables are gender, student, status, and ethnicity. Additonally, the quantitative variables are balance, age, cards, education, income, limit, and rating.

The report is based on **Credit.csv** data set, but all of our analysis is done using **scaled-credit.csv**, which is a standardized version of the original credit data set. To create this new data set we perform mean centering and standardizing(mean zero and sd is one) because we want to have comparable scales to prevent favoritism for certain coefficients. We also scale our data because *glmnet()*, the function we will use for ridge and lasso regressions, does not take factors as data. 

Once we perform analysis on **scaled-credit.csv** using our various regression methods we create various Rdata files with summary statistics for each respective method. These Rdata files are:
	
* OLS_regression.Rdata 

* ridge-regression.Rdata 

* lasso.Rdata

* pc-regression.Rdata 

* plsr_regression.Rdata 


We also create various text files containing summary statistics for each respective method. These text files are:

* ols_regression_output.txt

* ridge-regression-output.txt 

* Lasso_regression.txt 

* pc-regression-output.txt

* plsr_regression.txt

Finally, **train_test.Rdata** contains the training and testing data sets for the regression models. The training data contains 300 elements and the testing data contains 100 elements. The elements of each set are randomized and meant to be reproducible since we set the seed in the script, which produced the 2 sets. The different use of these two sets will be explained in the next section.

